Change status into peers

diff --git a/ads-monitor b/ads-monitor
--- a/ads-monitor
+++ b/ads-monitor
@@ -6,121 +6,6 @@ date_msg()
     echo "$(date +'%F %T') | $(date --date=@$1 +'%F %T')  $2"
 }
 
-get_opt() {
-    line=`grep -i $2= $1/options.cfg | head -1`
-    if [[ ${line} =~ ^$2=(.+)$ ]]; then
-        echo ${BASH_REMATCH[1]}
-    else
-        >&2 echo "Cannot find options $2"
-        exit 1
-    fi
-}
-
-get_addr() {
-    get_opt $1 "addr"
-}
-
-get_port() {
-    get_opt $1 "port"
-}
-
-get_offi() {
-    get_opt $1 "offi"
-}
-
-get_svid() {
-    get_opt $1 "svid"
-}
-
-check_stderr() {
-
-	if [ ! -d $1 ]; then
-	    echo "The node has not been configured - cannot find working directory \"$1\""
-		return 1
-	fi
-
-	if [ ! -f $2 ]; then
-        echo "The node has not been started - cannot find STDERR file \"$2\""
-		return 2
-	fi
-
-	line=`tac $2 | grep -m 1 .`
-    regex="^\[([0-9]+)\]"
-
-    if [[ ${line} =~ ${regex} ]]; then
-		if [ $(date +"%s") -ge $((BASH_REMATCH[1] + 3)) ]; then
-            echo "The node seems to be dead"
-	        return 3
-		fi
-	else
-        echo "Cannot parse STDERR file \"$2\""
-		return 21
-	fi
-
-	return 0
-}
-
-# Checks if the node is alive
-status() {
-
-    if ! host=`get_addr $1`; then
-        if [ -n "$3" ]; then
-            >&2 echo "-11  Cannot find host in \"$1\""
-        else
-            >&2 echo -11
-        fi
-        return
-    fi
-    if ! port=`get_offi $1`; then
-        if [ -n "$3" ]; then
-            >&2 echo "-12  Cannot find port in \"$1\""
-        else
-            >&2 echo -12
-        fi
-        return
-    fi
-    if ! node_id=`get_svid $1`; then
-        if [ -n "$3" ]; then
-            >&2 echo "-13  Cannot find node number in \"$1\""
-        else
-            >&2 echo -13
-        fi
-        return
-    fi
-
-	line=`tac $2 | grep -m 1 .`
-    regex="^\[([0-9]+)\]\ Awaiting for genesis block time:\ ([0-9]+\ s)"
-
-    if [[ ${line} =~ ${regex} ]]; then
-        if [ -n "$3" ]; then
-            date_msg ${BASH_REMATCH[1]} "The node will start in ${BASH_REMATCH[2]} | ${host}:${port} ${node_id}"
-        else
-            echo ${node_id}
-        fi
-    else
-	    data=`echo '{"run":"get_me"}' | ads -H${host} -P${port} --work-dir=$1 --secret=123 2> /dev/null`
-	    if [[ ${data} =~ \"current_block_time\":\ \"([0-9]+)\".*\"previous_block_time\":\ \"([0-9]+)\" ]]; then
-	        if [ -n "$3" ]; then
-	            date_msg ${BASH_REMATCH[2]} "->  $(date --date=@${BASH_REMATCH[1]} +'%F %T') | ${host}:${port} ${node_id}"
-	        else
-	            echo ${node_id}
-	        fi
-	    elif [[ ${data} =~ \"error\":\ \"(.+)\" ]]; then
-	        if [ -n "$3" ]; then
-	            echo "-31  Response error: ${BASH_REMATCH[1]}"
-	        else
-	            echo -31
-	        fi
-	    else
-	        if [ -n "$3" ]; then
-	            echo "-32  Cannot parse 'get_block' response"
-	        else
-	            echo -32
-	        fi
-	    fi
-	fi
-}
-
 # Calculating transactions per second
 tps() {
     actual_txs=
@@ -157,6 +42,19 @@ tps() {
 
 # Parsing CLOCK log
 clock() {
+
+	line=`tac $2 | grep -m 1 .`
+    regex="^\[([0-9]+)\]\ Awaiting for genesis block time:\ ([0-9]+\ s)"
+
+    if [[ ${line} =~ ${regex} ]]; then
+        if [ -n "$3" ]; then
+            >&2 date_msg ${BASH_REMATCH[1]} "The node will start in ${BASH_REMATCH[2]}"
+        else
+            echo -1
+        fi
+		exit 1
+    fi
+
     line=`tac $2 | grep CLOCK | head -1`
     regex="^\[([0-9]+)\]\ CLOCK:\ ([0-9A-F]+).*\ $1:([0-9]+)"
 
@@ -183,28 +81,6 @@ clock() {
     fi
 }
 
-# Parsing log
-log() {
-    line=`tac $3 | grep "$1" | head -1`
-    regex="^\[([0-9]+)\]\ .*\ $2:([0-9]+)"
-
-    if [[ ${line} =~ ${regex} ]]; then
-
-        time=${BASH_REMATCH[1]}
-        val=${BASH_REMATCH[2]}
-
-        if [ -n "$4" ]; then
-            date_msg ${time} ${val}
-        else
-            echo ${val}
-        fi
-
-    else
-        >&2 echo "-22 Cannot find $1 log"
-        exit -22
-    fi
-}
-
 # Number of awaiting transactions
 txs() {
     clock "txs" $1 $2
@@ -215,9 +91,43 @@ peers() {
     clock "peers" $1 $2
 }
 
+# Checks if the node is alive
+status() {
+    peers $1 $2
+}
+
 # Number of currently open connections
 connections() {
     clock "ticket" $1 $2
+}
+
+# Check node configuration
+check_stderr() {
+
+	if [ ! -d $1 ]; then
+	    echo "The node has not been configured - cannot find working directory \"$1\""
+		return 11
+	fi
+
+	if [ ! -f $2 ]; then
+        echo "The node has not been started - cannot find STDERR file \"$2\""
+		return 12
+	fi
+
+	line=`tac $2 | grep -m 1 .`
+    regex="^\[([0-9]+)\]"
+
+    if [[ ${line} =~ ${regex} ]]; then
+		if [ $(date +"%s") -ge $((BASH_REMATCH[1] + 3)) ]; then
+            echo "The node seems to be dead"
+	        return 13
+		fi
+	else
+        echo "Cannot parse STDERR file \"$2\""
+		return 21
+	fi
+
+	return 0
 }
 
 # Display error message
@@ -330,19 +240,21 @@ fi
 
 stderr_path=`readlink -m ${stderr_path}`
 
-if ! message=$(check_stderr ${working_dir} ${stderr_path}) ; then
+message=$(check_stderr ${working_dir} ${stderr_path})
+err=$?
+if [ ${err} -gt 0 ] ; then
 	if [ -n "${verbose}" ]; then
-        >&2 echo "$(( $# * -1 )) ${message}"
+        >&2 echo "Error ${err}: ${message}"
     else
-        >&2 echo $(( $# * -1 ))
+        >&2 echo $(( ${err} * -1 ))
     fi
-    exit 1
+    exit ${err}
 fi
 
 # Parsing command
 command=
 case "$1" in
-    status) command="status ${working_dir} ${stderr_path} ${verbose}" ;;
+    status) command="status ${stderr_path} ${verbose}" ;;
     tps)    command="tps ${stderr_path} ${verbose}" ;;
     txs)    command="txs ${stderr_path} ${verbose}" ;;
     peers)  command="peers ${stderr_path} ${verbose}" ;;
