Checking node configuration in continuous mode

diff --git a/ads-monitor b/ads-monitor
--- a/ads-monitor
+++ b/ads-monitor
@@ -142,30 +142,42 @@ connections() {
 # Check node configuration
 check_stderr() {
 
-	if [ ! -d $1 ]; then
-	    echo "The node has not been configured - cannot find working directory \"$1\""
-		return 11
-	fi
+	err=0
 
-	if [ ! -f $2 ]; then
-        echo "The node has not been started - cannot find STDERR file \"$2\""
-		return 12
-	fi
-
-	line=`tac $2 | grep -m 1 .`
-    regex="^\[([0-9]+)\]"
-
-    if [[ ${line} =~ ${regex} ]]; then
-		if [ $(date +"%s") -ge $((BASH_REMATCH[1] + 3)) ]; then
-            echo "The node seems to be dead"
-	        return 13
-		fi
+	if [ ! -d ${working_dir} ]; then
+	    message="The node has not been configured - cannot find working directory \"${working_dir}\""
+		err=11
+	elif [ ! -f ${stderr_path} ]; then
+        message="The node has not been started - cannot find STDERR file \"${stderr_path}\""
+		err=12
 	else
-        echo "Cannot parse STDERR file \"$2\""
-		return 21
+		line=`tac ${stderr_path} | grep -m 1 .`
+	    regex="^\[([0-9]+)\]"
+	    if [[ ${line} =~ ${regex} ]]; then
+			if [ $(date +"%s") -ge $((BASH_REMATCH[1] + 3)) ]; then
+	            message="The node seems to be dead"
+		        err=13
+			fi
+		else
+	        message="Cannot parse STDERR file \"${stderr_path}\""
+			err=21
+		fi
 	fi
 
-	return 0
+	if [ ${err} -gt 0 ] ; then
+		if [ "${cmd}" = "status" ]; then
+			if [ -n "${verbose}" ]; then
+		        echo "Error ${err}: ${message}"
+		    else
+		        echo ${err}
+		    fi
+		    exit
+		else
+		    >&2 echo "Error ${err}: ${message}"
+		    echo 0
+		    exit ${err}
+		fi
+	fi
 }
 
 # Display error message
@@ -264,6 +276,8 @@ if [ -n "$2" ]; then
     show_error "To many arguments"
 fi
 
+cmd=$1
+
 # Checking paths and dirs
 
 if [ -z "$working_dir" ]; then
@@ -278,41 +292,26 @@ fi
 
 stderr_path=`readlink -m ${stderr_path}`
 
-message=$(check_stderr ${working_dir} ${stderr_path})
-err=$?
-if [ ${err} -gt 0 ] ; then
-	if [ "$1" = "status" ]; then
-		if [ -n "${verbose}" ]; then
-	        echo "Error ${err}: ${message}"
-	    else
-	        echo ${err}
-	    fi
-	    exit
-	else
-	    >&2 echo "Error ${err}: ${message}"
-	    echo 0
-	    exit ${err}
-	fi
-fi
-
 # Parsing command
 command=
-case "$1" in
+case "${cmd}" in
     status) command="status ${stderr_path} ${verbose}" ;;
     tps)    command="tps ${stderr_path} ${verbose}" ;;
     txs)    command="txs ${stderr_path} ${verbose}" ;;
     peers)  command="peers ${stderr_path} ${verbose}" ;;
     conns)  command="connections ${stderr_path} ${verbose}" ;;
-    *)      show_error "Unsupported command \"$1\"" ;;
+    *)      show_error "Unsupported command \"${cmd}\"" ;;
 esac
 
 # Runs the monitor in a loop
-if [ -n "$continuous" ]; then
+if [ -n "${continuous}" ]; then
     while true; do
+        check_stderr
         ${command}
         sleep 1
     done
 else
+	check_stderr
 	${command};
 	err=$?
     if [ ${err} -gt 0 ]; then
