Print errors on stderr

diff --git a/ads-monitor b/ads-monitor
--- a/ads-monitor
+++ b/ads-monitor
@@ -47,12 +47,18 @@ clock() {
     regex="^\[([0-9]+)\]\ Awaiting for genesis block time:\ ([0-9]+\ s)"
 
     if [[ ${line} =~ ${regex} ]]; then
-        if [ -n "$3" ]; then
-            >&2 date_msg ${BASH_REMATCH[1]} "The node will start in ${BASH_REMATCH[2]}"
-        else
-            echo -1
-        fi
-		exit 1
+	    if [ -n "$4" ]; then
+			 if [ -n "$3" ]; then
+		        date_msg ${BASH_REMATCH[1]} "The node will start in ${BASH_REMATCH[2]}"
+		    else
+		        echo 1
+		    fi
+		    return
+		else
+	        >&2 date_msg ${BASH_REMATCH[1]} "The node will start in ${BASH_REMATCH[2]}"
+	        echo 0
+			return 1
+		fi
     fi
 
     line=`tac $2 | grep CLOCK | head -1`
@@ -66,18 +72,25 @@ clock() {
 
         if [ -n "$3" ]; then
             date_msg ${time} "0x${clock: -3}  ${val}"
+        elif [ -n "$4" ]; then
+            echo $(( 100 + ${val} ))
         else
             echo ${val}
         fi
 
     else
-
-        if [ -n "$3" ]; then
-            >&2 echo "-22 Cannot find CLOCK log"
-        else
-            echo -22
-        fi
-        exit 1
+	    if [ -n "$4" ]; then
+			 if [ -n "$3" ]; then
+		        echo "Error 22: Cannot find CLOCK log"
+		    else
+		        echo 22
+		    fi
+		    exit
+		else
+	        >&2 echo "Error 22: Cannot find CLOCK log"
+	        echo 0
+	        exit 22
+	     fi
     fi
 }
 
@@ -93,7 +106,7 @@ peers() {
 
 # Checks if the node is alive
 status() {
-    peers $1 $2
+    clock "peers" $1 "$2" 1
 }
 
 # Number of currently open connections
@@ -243,12 +256,18 @@ stderr_path=`readlink -m ${stderr_path}`
 message=$(check_stderr ${working_dir} ${stderr_path})
 err=$?
 if [ ${err} -gt 0 ] ; then
-	if [ -n "${verbose}" ]; then
-        >&2 echo "Error ${err}: ${message}"
-    else
-        >&2 echo $(( ${err} * -1 ))
-    fi
-    exit ${err}
+	if [ "$1" = "status" ]; then
+		if [ -n "${verbose}" ]; then
+	        echo "Error ${err}: ${message}"
+	    else
+	        echo ${err}
+	    fi
+	    exit
+	else
+	    >&2 echo "Error ${err}: ${message}"
+	    echo 0
+	    exit ${err}
+	fi
 fi
 
 # Parsing command
@@ -269,5 +288,9 @@ if [ -n "$continuous" ]; then
         sleep 1
     done
 else
-    ${command}
+	${command};
+	err=$?
+    if [ ${err} -gt 0 ]; then
+        exit ${err}
+    fi
 fi
